server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prd-codeit-4.cl6yoym4c9bq.ap-northeast-2.rds.amazonaws.com:3306/codeit?useSSL=false&serverTimezone=UTC
    username: codeit
    password: Codeit4team!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  mapper-locations: classpath*:codeit/sqlmap/mapper/*-mapper.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-handlers-package: come.codeit.server.config